"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { axiosSecure } from "@/lib/axios";
import axios from "axios";
import toast from "react-hot-toast";

export default function EditRecipePage(){
 const {id}=useParams(); const router=useRouter(); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [file,setFile]=useState(null); const [preview,setPreview]=useState("");
 const [form,setForm]=useState({recipeName:"",category:"",cuisineType:"",difficultyLevel:"",preparationTime:"",ingredients:"",instructions:"",recipeImage:""});
 useEffect(()=>{(async()=>{try{const r=await axiosSecure.get(`/recipes/${id}`);const x=r.data;setForm({recipeName:x.recipeName||"",category:x.category||"",cuisineType:x.cuisineType||"",difficultyLevel:x.difficultyLevel||"",preparationTime:x.preparationTime||"",ingredients:(x.ingredients||[]).join(", "),instructions:(x.instructions||[]).join("\n"),recipeImage:x.recipeImage||""});setPreview(x.recipeImage||"");}catch(e){toast.error(e.response?.data?.message||"Failed to load recipe");}finally{setLoading(false)}})()},[id]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setSaving(true);try{let image=form.recipeImage;if(file){const fd=new FormData();fd.append("image",file);const key=process.env.NEXT_PUBLIC_IMGBB_API_KEY;if(!key) throw new Error("NEXT_PUBLIC_IMGBB_API_KEY is missing");const r=await axios.post(`https://api.imgbb.com/1/upload?key=${key}`,fd);image=r.data.data.display_url;}await axiosSecure.patch(`/recipes/${id}`,{recipeName:form.recipeName,category:form.category,cuisineType:form.cuisineType,difficultyLevel:form.difficultyLevel,preparationTime:form.preparationTime,ingredients:form.ingredients.split(",").map(x=>x.trim()).filter(Boolean),instructions:form.instructions.split("\n").map(x=>x.trim()).filter(Boolean),recipeImage:image});toast.success("Recipe updated successfully");router.push("/dashboard/my-recipes");}catch(e){toast.error(e.response?.data?.message||e.message||"Update failed");}finally{setSaving(false)}};
 if(loading)return <div className="p-10 text-center">Loading recipe...</div>;
 const input="w-full px-4 py-3 rounded-xl border border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white outline-none";
 return <div className="max-w-4xl mx-auto"><h1 className="text-3xl font-black text-gray-900 dark:text-white mb-7">Edit Recipe</h1><form onSubmit={submit} className="bg-white dark:bg-gray-900 border dark:border-gray-800 rounded-2xl p-6 md:p-10 space-y-6"><div className="grid md:grid-cols-2 gap-5"><input className={input} name="recipeName" value={form.recipeName} onChange={change} required placeholder="Recipe Name"/><select className={input} name="category" value={form.category} onChange={change} required><option value="">Select Category</option>{["Breakfast","Lunch","Dinner","Dessert","Snack"].map(x=><option key={x}>{x}</option>)}</select><input className={input} name="cuisineType" value={form.cuisineType} onChange={change} required placeholder="Cuisine Type"/><select className={input} name="difficultyLevel" value={form.difficultyLevel} onChange={change} required><option value="">Difficulty</option>{["Easy","Medium","Hard"].map(x=><option key={x}>{x}</option>)}</select><input className={input} name="preparationTime" value={form.preparationTime} onChange={change} required placeholder="Preparation Time"/></div><textarea className={input} name="ingredients" value={form.ingredients} onChange={change} required rows="4" placeholder="Ingredients separated by commas"/><textarea className={input} name="instructions" value={form.instructions} onChange={change} required rows="7" placeholder="One instruction per line"/><div><label className="block font-bold text-gray-700 dark:text-gray-300 mb-2">Recipe Image</label>{preview&&<img src={preview} alt="Current" className="w-40 h-28 object-cover rounded-xl mb-3"/>}<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){setFile(f);setPreview(URL.createObjectURL(f))}}}/></div><button disabled={saving} className="w-full py-3.5 rounded-xl bg-orange-600 hover:bg-orange-700 text-white font-bold disabled:opacity-60">{saving?"Updating...":"Update Recipe"}</button></form></div>;
}
